In [26]:
import numpy as np
import random

In [2]:
python_list=range(10000)

In [23]:
list1=[1,2,3,4,5,6,76,8,9]

In [4]:
python_array=np.arange(10000)

In [11]:
%%timeit
for i in range(1000):
    result= python_array*5

18.9 ms ± 1.79 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [12]:
%%timeit
for i in range(1000):
    result=[j*5 for j in python_list]


2.04 s ± 293 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [20]:
ar1=np.ones((10,5))
ar1

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [21]:
ar1*2

array([[2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.],
       [2., 2., 2., 2., 2.]])

In [29]:
np.zeros((2,2,3))

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])