# Topic:
- more about numpy and its functions 

In [1]:
import numpy as np

### Vectorized operations

In [6]:
v=np.zeros((4,6))
v

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [7]:
v+10

array([[10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10.],
       [10., 10., 10., 10., 10., 10.]])

In [8]:
y=np.ones((4,6))

In [9]:
v+y

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [10]:
l1=[1,2,3,4,5,6]
l2=[2,6,7,9,4,6]    

In [13]:
sum=[]
for i,val in enumerate(l1):
    sum.append(l1[i]+l2[i])


In [14]:
sum

[3, 8, 10, 13, 9, 12]

In [15]:
l1+l2

[1, 2, 3, 4, 5, 6, 2, 6, 7, 9, 4, 6]

In [16]:
salary=np.array([20,50,60,12,10,6,16])

In [21]:
np.where(salary>21,salary*1.05,salary*1.10)

array([22. , 52.5, 63. , 13.2, 11. ,  6.6, 17.6])

In [22]:
salary.dtype

dtype('int32')

In [28]:
x=np.arange(1,101).reshape((10,10))
x

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [ 11,  12,  13,  14,  15,  16,  17,  18,  19,  20],
       [ 21,  22,  23,  24,  25,  26,  27,  28,  29,  30],
       [ 31,  32,  33,  34,  35,  36,  37,  38,  39,  40],
       [ 41,  42,  43,  44,  45,  46,  47,  48,  49,  50],
       [ 51,  52,  53,  54,  55,  56,  57,  58,  59,  60],
       [ 61,  62,  63,  64,  65,  66,  67,  68,  69,  70],
       [ 71,  72,  73,  74,  75,  76,  77,  78,  79,  80],
       [ 81,  82,  83,  84,  85,  86,  87,  88,  89,  90],
       [ 91,  92,  93,  94,  95,  96,  97,  98,  99, 100]])

In [30]:
x.transpose()

array([[  1,  11,  21,  31,  41,  51,  61,  71,  81,  91],
       [  2,  12,  22,  32,  42,  52,  62,  72,  82,  92],
       [  3,  13,  23,  33,  43,  53,  63,  73,  83,  93],
       [  4,  14,  24,  34,  44,  54,  64,  74,  84,  94],
       [  5,  15,  25,  35,  45,  55,  65,  75,  85,  95],
       [  6,  16,  26,  36,  46,  56,  66,  76,  86,  96],
       [  7,  17,  27,  37,  47,  57,  67,  77,  87,  97],
       [  8,  18,  28,  38,  48,  58,  68,  78,  88,  98],
       [  9,  19,  29,  39,  49,  59,  69,  79,  89,  99],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])

In [31]:
arr=np.array([1,5,3,2,7,8])

In [32]:
arr.mean()

4.333333333333333

In [33]:
arr.cumsum()

array([ 1,  6,  9, 11, 18, 26])

In [34]:
arr.cumprod()

array([   1,    5,   15,   30,  210, 1680])

In [35]:
arr

array([1, 5, 3, 2, 7, 8])

In [36]:
arr.sort()

In [37]:
arr

array([1, 2, 3, 5, 7, 8])

In [38]:
arr2=np.array([2,2,4,6,7,8,9,1,2])

In [40]:
un=np.unique(arr2)

In [41]:
un

array([1, 2, 4, 6, 7, 8, 9])

In [42]:
np.save("unique",un)

In [43]:
load=np.load("unique.npy")

In [45]:
load

array([1, 2, 4, 6, 7, 8, 9])

In [46]:
arr=np.arange(16).reshape((4,4))

In [47]:
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [48]:
arr.diagonal()

array([ 0,  5, 10, 15])

In [49]:
arr.trace()

30

In [50]:
arr1=np.arange(10,26).reshape((4,4))

In [51]:
arr.dot(arr1)

array([[ 116,  122,  128,  134],
       [ 372,  394,  416,  438],
       [ 628,  666,  704,  742],
       [ 884,  938,  992, 1046]])

In [52]:
from numpy import linalg

In [55]:
linalg.det(arr1)

0.0

In [54]:
linalg.inv(arr)

LinAlgError: Singular matrix

In [56]:
linalg.eigvals(arr)

array([ 3.24642492e+01, -2.46424920e+00,  1.64176007e-15, -1.10576860e-16])

In [57]:
np.random.normal(3,4,(2,5))

array([[-1.02907431, 10.58425747,  8.26649687, -0.46446187,  1.84942145],
       [ 6.06497352,  7.64860079, 11.67169767,  1.71574653,  1.49330291]])

In [58]:
np.random.gamma(3,5,(3,5))

array([[ 7.93406073, 37.63782765, 13.02084119, 22.17326655, 12.82541711],
       [27.00310866, 17.53649304, 11.40981743, 23.41185764, 11.93443596],
       [17.27059277, 20.73069988, 10.75571616,  7.90284164, 23.96894402]])

In [60]:
arr = np.arange(16)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [65]:
arr.reshape((4,4),order="C")

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [66]:
arr = np.array([[1,8,7],[3,4,5],[9,0,1]])

In [71]:
arr

array([[1, 8, 7],
       [3, 4, 5],
       [9, 0, 1]])

In [70]:
arr.ravel()

array([1, 8, 7, 3, 4, 5, 9, 0, 1])

In [72]:
a = np.array([[1,2],[3,4]])
b = np.array([[7,8],[9,10]])

In [74]:
print(a)
print(b)

[[1 2]
 [3 4]]
[[ 7  8]
 [ 9 10]]


In [76]:
np.concatenate((a,b),axis=1)

array([[ 1,  2,  7,  8],
       [ 3,  4,  9, 10]])